services:
  db:
    image: postgres:16-alpine
    container_name: wm_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: WarehouseDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    mem_limit: 512m

  pgadmin:
    image: dpage/pgadmin4
    container_name: wm_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@warehouse.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    mem_limit: 384m

volumes:
  postgres_data: